// Data from https://www.nmra.org/sites/default/files/standards/sandrp/pdf/s-9.2.2_decoder_cvs_2012.07.pdf
export const CvNames = {
    1: "Primary Address",
    2: "Vstart",
    3: "Acceleration Rate",
    4: "Deceleration Rate",
    5: "Vhigh",
    6: "Vmid",
    7: "Manufacturer Version No.",
    8: "Manufactured ID",
    9: "Total PWM Period",
    10: "EMF Feedback Cutout",
    11: "Packet Time-Out Value",
    12: "Power Source Conversion",
    13: "Alternate Mode Function. Status F1-F8",
    14: "Alternate Mode Function. Status FL,F9-F12",
    15: "Decoder Lock",
    16: "Decoder Lock",
    17: "Extended Address High Byte",
    18: "Extended Address Low Byte",
    19: "Consist Address",
    // 20: Reserved
    21: "Consist Addr Active for F1-F8",
    22: "Consist Addr Active for FL-F9-F12",
    23: "Acceleration Adjustment",
    24: "Deceleration Adjustment",
    25: "Speed Table/Mid-range Cab Speed Step",
    // 26: Reserved
    27: "Decoder Automatic Stopping Configuration",
    28: "Bi-Directional Communication Configuration",
    29: "Configuration Data",
    30: "Error Information",
    31: "Index High Byte",
    32: "Index Low Byte",
    65: "Kick Start",
    66: "Forward Trim",
    95: "Reverse Trim",
    105: "User Identifier #1",
    106: "User Identifier #2"
};