#!/bin/sh
# /etc/init.d/itokawa

### BEGIN INIT INFO
# Provides: itokawa
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start: 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start Application
# Description: Start Itokawa automatically.
### END INIT INFO

# User to launch server using
USER=pi
# Directory containing server code
APP_DIR=/home/$USER/Itokawa
# Path to pid file
PID_FILE=/home/$USER/.itokawa/pid

case "$1" in
start)
    cd $APP_DIR
    su $USER -c 'npm start > ~/.itokawa/itokawa.log 2>&1 &'
;;
stop)
    if test -f "$PID_FILE"; then
        kill `cat $PID_FILE`
        rm "$PID_FILE"
    else
        echo "Itokawa doesn't appear to be running"
    fi
;;
*)
echo "Usage: itokawa {start|stop}"
exit 1
;;
esac
exit 0